### ISSUE TITLE
CMake INSTALL step not working

### ISSUE THREAD

**Issue by Varser** [SemaiCZE/inicpp#1]
Operating system - Windows 10.

Steps to reproduce:
1. git clone --recursive -j8 https://github.com/SemaiCZE/inicpp.git
2. mkdir build
3. cd build
4. cmake.exe -G "Microsoft Visual Studio 14 2015" ..\
5. Open generated project in VS2015 as administrator
6. Run All_BUILD
7. Run INSTALL

But nothing were installed in "Program Files" folder

Expexted behavior:
headers and dlls should be placed in "C:\Program Files (x86)\inicpp.

**Comment by SemaiCZE** [comment]
Hi,
Thank you for your interest in this library. Now we don't support installation, because our thoughts about usage were more like pack this library with project instead of installing it system wide. But we already have some tasks to do in future and installation is one of them. As you wish, we'll try to complete it soon. Or if you want, pull requests are welcome ;). Starting point could be something like [this](https://github.com/ReCodEx/worker/blob/master/CMakeLists.txt#L264).
Thanks.
